# Generated by Django 4.2.7 on 2024-04-13 15:49

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('location', models.CharField(choices=[('Adabraka', 'Adabraka'), ('Airport Residential Area', 'Airport Residential Area'), ('Cantonments', 'Cantonments'), ('Dansoman', 'Dansoman'), ('Dzorwulu', 'Dzorwulu'), ('East Legon', 'East Legon'), ('Haatso', 'Haatso'), ('Kaneshie', 'Kaneshie'), ('Labadi', 'Labadi'), ('Madina', 'Madina'), ('Mamprobi', 'Mamprobi'), ('Nima', 'Nima'), ('North Ridge', 'North Ridge'), ('Osu', 'Osu'), ('Ridge', 'Ridge'), ('Sakumono', 'Sakumono'), ('Spintex', 'Spintex'), ('Tema', 'Tema'), ('Teshie', 'Teshie'), ('West Legon', 'West Legon')], max_length=100)),
                ('price', models.CharField(default=0, max_length=50)),
                ('description', models.CharField(default='', max_length=200)),
                ('contact', models.CharField(default=0, max_length=50)),
                ('property_type', models.CharField(default='', max_length=100)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('ghcard', models.CharField(max_length=50)),
                ('user_type', models.CharField(choices=[('LL', 'Landlord'), ('TT', 'Tenant')], default='TT', max_length=50)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
