# Generated by Django 4.2.7 on 2024-04-03 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='bathroom_availability',
        ),
        migrations.RemoveField(
            model_name='property',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='property',
            name='electricity_availability',
        ),
        migrations.RemoveField(
            model_name='property',
            name='gps_location',
        ),
        migrations.RemoveField(
            model_name='property',
            name='kitchen_availability',
        ),
        migrations.RemoveField(
            model_name='property',
            name='name',
        ),
        migrations.RemoveField(
            model_name='property',
            name='number_of_rooms',
        ),
        migrations.RemoveField(
            model_name='property',
            name='pictures',
        ),
        migrations.RemoveField(
            model_name='property',
            name='property_type',
        ),
        migrations.RemoveField(
            model_name='property',
            name='rent_status',
        ),
        migrations.RemoveField(
            model_name='property',
            name='review',
        ),
        migrations.RemoveField(
            model_name='property',
            name='water_availability',
        ),
        migrations.AddField(
            model_name='property',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='image',
            field=models.ImageField(null=True, upload_to='property_images/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
