# Generated by Django 4.2.7 on 2024-04-08 21:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_remove_property_bathroom_availability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='contact',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='property',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='location',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
