# Generated by Django 4.2.7 on 2024-04-09 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0003_property_contact_alter_property_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.CharField(default='', max_length=100),
        ),
    ]
