# Generated by Django 4.2.7 on 2024-04-11 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0004_property_property_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
